In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [4]:
df['Purchased'].unique()

array(['No', 'Yes'], dtype=object)

In [5]:
df['Country'].value_counts()

France     4
Spain      3
Germany    3
Name: Country, dtype: int64

In [6]:
df['Purchased'].value_counts()

No     5
Yes    5
Name: Purchased, dtype: int64

In [7]:
one_hot=pd.get_dummies(df,columns=['Country','Purchased'])
one_hot

Age   Salary  Country_France  Country_Germany  Country_Spain  \
0  44.0  72000.0               1                0              0   
1  27.0  48000.0               0                0              1   
2  30.0  54000.0               0                1              0   
3  38.0  61000.0               0                0              1   
4  40.0      NaN               0                1              0   
5  35.0  58000.0               1                0              0   
6   NaN  52000.0               0                0              1   
7  48.0  79000.0               1                0              0   
8  50.0  83000.0               0                1              0   
9  37.0  67000.0               1                0              0   

   Purchased_No  Purchased_Yes  
0             1              0  
1             0              1  
2             1              0  
3             1              0  
4             0              1  
5             0              1  
6             1              0  
7             0              1  
8             1              0  
9             0              1

In [8]:
import pandas as pd
import numpy as np


In [9]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [10]:
import sklearn
from sklearn.preprocessing import OneHotEncoder

In [11]:
df['Country']=df['Country'].astype('category')
df['Purchased']=df['Purchased'].astype('category')
df['Purchased']

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: category
Categories (2, object): ['No', 'Yes']

In [12]:
df['Country']

0     France
1      Spain
2    Germany
3      Spain
4    Germany
5     France
6      Spain
7     France
8    Germany
9     France
Name: Country, dtype: category
Categories (3, object): ['France', 'Germany', 'Spain']

In [13]:
df['Purch_new']=df['Purchased'].cat.codes
df['Count_new']=df['Country'].cat.codes

In [14]:
df['Purch_new']

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purch_new, dtype: int8

In [15]:
one=OneHotEncoder()

In [16]:
df1=pd.DataFrame(one.fit_transform(df[['Purch_new','Count_new']]).toarray())
df1

0    1    2    3    4
0  1.0  0.0  1.0  0.0  0.0
1  0.0  1.0  0.0  0.0  1.0
2  1.0  0.0  0.0  1.0  0.0
3  1.0  0.0  0.0  0.0  1.0
4  0.0  1.0  0.0  1.0  0.0
5  0.0  1.0  1.0  0.0  0.0
6  1.0  0.0  0.0  0.0  1.0
7  0.0  1.0  1.0  0.0  0.0
8  1.0  0.0  0.0  1.0  0.0
9  0.0  1.0  1.0  0.0  0.0

In [17]:
df2=df.join(df1)

In [18]:
df2

Country   Age   Salary Purchased  Purch_new  Count_new    0    1    2    3  \
0   France  44.0  72000.0        No          0          0  1.0  0.0  1.0  0.0   
1    Spain  27.0  48000.0       Yes          1          2  0.0  1.0  0.0  0.0   
2  Germany  30.0  54000.0        No          0          1  1.0  0.0  0.0  1.0   
3    Spain  38.0  61000.0        No          0          2  1.0  0.0  0.0  0.0   
4  Germany  40.0      NaN       Yes          1          1  0.0  1.0  0.0  1.0   
5   France  35.0  58000.0       Yes          1          0  0.0  1.0  1.0  0.0   
6    Spain   NaN  52000.0        No          0          2  1.0  0.0  0.0  0.0   
7   France  48.0  79000.0       Yes          1          0  0.0  1.0  1.0  0.0   
8  Germany  50.0  83000.0        No          0          1  1.0  0.0  0.0  1.0   
9   France  37.0  67000.0       Yes          1          0  0.0  1.0  1.0  0.0   

     4  
0  0.0  
1  1.0  
2  0.0  
3  1.0  
4  0.0  
5  0.0  
6  1.0  
7  0.0  
8  0.0  
9  0.0

In [19]:
import pandas as pd

In [20]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [21]:
print(df[['Country','Purchased']])
import sklearn
from sklearn.preprocessing import OrdinalEncoder
enc=OrdinalEncoder()
data=enc.fit_transform(df[['Country','Purchased']])
print(data)

   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes
[[0. 0.]
 [2. 1.]
 [1. 0.]
 [2. 0.]
 [1. 1.]
 [0. 1.]
 [2. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


In [22]:
print(df[['Country','Purchased']])
import sklearn
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(sparse=False)
data=enc.fit_transform(df[['Country','Purchased']])
print(data)

   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes
[[1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


In [23]:
print(df[['Country','Purchased']])
import sklearn
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(drop='first',sparse=False)
data=enc.fit_transform(df[['Country','Purchased']])
print(data)

   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes
[[0. 0. 0.]
 [0. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [24]:
import pandas as pd


In [25]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [26]:
df=pd.get_dummies(data=df,columns=['Country'])
df

Age   Salary Purchased  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0        No               1                0              0
1  27.0  48000.0       Yes               0                0              1
2  30.0  54000.0        No               0                1              0
3  38.0  61000.0        No               0                0              1
4  40.0      NaN       Yes               0                1              0
5  35.0  58000.0       Yes               1                0              0
6   NaN  52000.0        No               0                0              1
7  48.0  79000.0       Yes               1                0              0
8  50.0  83000.0        No               0                1              0
9  37.0  67000.0       Yes               1                0              0

In [27]:
df['Age'].isna().sum()

1

In [28]:
df['Salary'].isna().sum()

1

In [29]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [30]:
X=df[['Age','Salary','Country_France','Country_Germany','Country_Spain']]
df['Purchased'] = df['Purchased'].apply(lambda x: 0 if x=='No' else 1)
X

Age        Salary  Country_France  Country_Germany  Country_Spain
0  44.000000  72000.000000               1                0              0
1  27.000000  48000.000000               0                0              1
2  30.000000  54000.000000               0                1              0
3  38.000000  61000.000000               0                0              1
4  40.000000  63777.777778               0                1              0
5  35.000000  58000.000000               1                0              0
6  38.777778  52000.000000               0                0              1
7  48.000000  79000.000000               1                0              0
8  50.000000  83000.000000               0                1              0
9  37.000000  67000.000000               1                0              0

In [31]:
y=df[['Purchased']]
y

Purchased
0          0
1          1
2          0
3          0
4          1
5          1
6          0
7          1
8          0
9          1

In [32]:
df

Age        Salary  Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000          0               1                0   
1  27.000000  48000.000000          1               0                0   
2  30.000000  54000.000000          0               0                1   
3  38.000000  61000.000000          0               0                0   
4  40.000000  63777.777778          1               0                1   
5  35.000000  58000.000000          1               1                0   
6  38.777778  52000.000000          0               0                0   
7  48.000000  79000.000000          1               1                0   
8  50.000000  83000.000000          0               0                1   
9  37.000000  67000.000000          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

In [33]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte=train_test_split(X,y,test_size=0.2)

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
knn=KNeighborsClassifier()

In [36]:
knn.fit(xtr,ytr)

C:\Users\SONIC LAPTOPS\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [37]:
y_pred=knn.predict(xte)

In [38]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred,yte))

0.0


In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
sc=StandardScaler()

In [41]:
df

Age        Salary  Purchased  Country_France  Country_Germany  \
0  44.000000  72000.000000          0               1                0   
1  27.000000  48000.000000          1               0                0   
2  30.000000  54000.000000          0               0                1   
3  38.000000  61000.000000          0               0                0   
4  40.000000  63777.777778          1               0                1   
5  35.000000  58000.000000          1               1                0   
6  38.777778  52000.000000          0               0                0   
7  48.000000  79000.000000          1               1                0   
8  50.000000  83000.000000          0               0                1   
9  37.000000  67000.000000          1               1                0   

   Country_Spain  
0              0  
1              1  
2              0  
3              1  
4              0  
5              0  
6              1  
7              0  
8              0  
9              0

In [42]:
sg=sc.fit_transform(df)
sg

array([[ 7.58874362e-01,  7.49473254e-01, -1.00000000e+00,
         1.22474487e+00, -6.54653671e-01, -6.54653671e-01],
       [-1.71150388e+00, -1.43817841e+00,  1.00000000e+00,
        -8.16496581e-01, -6.54653671e-01,  1.52752523e+00],
       [-1.27555478e+00, -8.91265492e-01, -1.00000000e+00,
        -8.16496581e-01,  1.52752523e+00, -6.54653671e-01],
       [-1.13023841e-01, -2.53200424e-01, -1.00000000e+00,
        -8.16496581e-01, -6.54653671e-01,  1.52752523e+00],
       [ 1.77608893e-01,  6.63219199e-16,  1.00000000e+00,
        -8.16496581e-01,  1.52752523e+00, -6.54653671e-01],
       [-5.48972942e-01, -5.26656882e-01,  1.00000000e+00,
         1.22474487e+00, -6.54653671e-01, -6.54653671e-01],
       [ 0.00000000e+00, -1.07356980e+00, -1.00000000e+00,
        -8.16496581e-01, -6.54653671e-01,  1.52752523e+00],
       [ 1.34013983e+00,  1.38753832e+00,  1.00000000e+00,
         1.22474487e+00, -6.54653671e-01, -6.54653671e-01],
       [ 1.63077256e+00,  1.75214693e+00, -1.000

In [43]:
sc=pd.DataFrame(data=sg,columns=['Age','Salary','Purchased','Country_France','Country_Germany','Country_Spain'])
sc

Age        Salary  Purchased  Country_France  Country_Germany  \
0  0.758874  7.494733e-01       -1.0        1.224745        -0.654654   
1 -1.711504 -1.438178e+00        1.0       -0.816497        -0.654654   
2 -1.275555 -8.912655e-01       -1.0       -0.816497         1.527525   
3 -0.113024 -2.532004e-01       -1.0       -0.816497        -0.654654   
4  0.177609  6.632192e-16        1.0       -0.816497         1.527525   
5 -0.548973 -5.266569e-01        1.0        1.224745        -0.654654   
6  0.000000 -1.073570e+00       -1.0       -0.816497        -0.654654   
7  1.340140  1.387538e+00        1.0        1.224745        -0.654654   
8  1.630773  1.752147e+00       -1.0       -0.816497         1.527525   
9 -0.258340  2.937125e-01        1.0        1.224745        -0.654654   

   Country_Spain  
0      -0.654654  
1       1.527525  
2      -0.654654  
3       1.527525  
4      -0.654654  
5      -0.654654  
6       1.527525  
7      -0.654654  
8      -0.654654  
9      -0.654654

In [44]:
X=sc[['Age','Salary','Country_France','Country_Germany','Country_Spain']]
X

Age        Salary  Country_France  Country_Germany  Country_Spain
0  0.758874  7.494733e-01        1.224745        -0.654654      -0.654654
1 -1.711504 -1.438178e+00       -0.816497        -0.654654       1.527525
2 -1.275555 -8.912655e-01       -0.816497         1.527525      -0.654654
3 -0.113024 -2.532004e-01       -0.816497        -0.654654       1.527525
4  0.177609  6.632192e-16       -0.816497         1.527525      -0.654654
5 -0.548973 -5.266569e-01        1.224745        -0.654654      -0.654654
6  0.000000 -1.073570e+00       -0.816497        -0.654654       1.527525
7  1.340140  1.387538e+00        1.224745        -0.654654      -0.654654
8  1.630773  1.752147e+00       -0.816497         1.527525      -0.654654
9 -0.258340  2.937125e-01        1.224745        -0.654654      -0.654654

In [45]:
y=sc.Purchased
y

0   -1.0
1    1.0
2   -1.0
3   -1.0
4    1.0
5    1.0
6   -1.0
7    1.0
8   -1.0
9    1.0
Name: Purchased, dtype: float64

In [46]:
from sklearn.model_selection import train_test_split
xtr,xte,ytr,yte = train_test_split(X, y, test_size=0.2)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(xtr, ytr)

from sklearn.metrics import accuracy_score
pred = knn.predict(xte)
print(accuracy_score(yte, pred))

0.0


In [47]:
mean=df['Purchased'].mean()
mean

0.5

In [48]:
df['Purchased']

0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int64

In [49]:
std=df['Purchased'].std()
std

0.5270462766947299

In [50]:
(  0-mean)/std

-0.9486832980505138

In [51]:
import pandas as pd
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [56]:
print(df[['Country','Purchased']])
import sklearn
from sklearn.preprocessing import LabelEncoder
enc=LabelEncoder()
print(enc.fit_transform(df[['Country']]))
print(enc.fit_transform(df[['Purchased']]))

   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes
[0 2 1 2 1 0 2 0 1 0]
[0 1 0 0 1 1 0 1 0 1]


C:\Users\SONIC LAPTOPS\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [67]:
import pandas as pd
import numpy as np

In [68]:
df=pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [83]:
print(df[['Country','Purchased']])
import sklearn
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(sparse=False)
data=ohe.fit_transform(df[['Country','Purchased']])
data

   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes


array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

In [77]:
print(df[['Country','Purchased']])
import sklearn
from sklearn.preprocessing import OneHotEncoder
enc=OneHotEncoder(sparse=False)
data=enc.fit_transform(df[['Country','Purchased']])
print(data)

   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes
[[1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [0. 0. 1. 1. 0.]
 [1. 0. 0. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 1.]]


In [85]:
print(df[['Country','Purchased']])
import sklearn
from sklearn.preprocessing import OrdinalEncoder
le=OrdinalEncoder()
data=le.fit_transform(df[['Country','Purchased']])
data

   Country Purchased
0   France        No
1    Spain       Yes
2  Germany        No
3    Spain        No
4  Germany       Yes
5   France       Yes
6    Spain        No
7   France       Yes
8  Germany        No
9   France       Yes


array([[0., 0.],
       [2., 1.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])